"""Add first and last name columns to users

Revision ID: 0a3a99a05fa5
Revises: 63d29e0ae1f8
Create Date: 2022-01-16 06:58:53.813415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3a99a05fa5'
down_revision = '63d29e0ae1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last')
    op.drop_column('users', 'first')
    # ### end Alembic commands ###
