version: '3'
services:

  "demo-nginx":
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./:/mnt
    depends_on:
      - demo-api-v201
    networks:
      - demo

  "demo-api-v201":
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
       - ./:/mnt
    entrypoint: "/bin/bash -c '/mnt/demo/start.bash'"
    stdin_open: true
    tty: true
    networks:
      - demo

  "demo-postgres":
    image: postgres:latest
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - demo
    ports:
      - 5432:5432
    container_name: "demo-postgres"

  "pgadmin":
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - demo
    ports:
      - 8080:80

networks:
  demo:
