version: '3'
services:

  "demo-bash":
    build:
      context: .
    volumes:
       - ./:/mnt
    entrypoint: "/bin/bash"
    stdin_open: true
    container_name: "demo-bash"
    tty: true
    networks:
      - demo

  "demo-api":
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
       - ./:/mnt
    entrypoint: "/bin/bash -c './demo/start.bash'"
    stdin_open: true
    container_name: "demo-api"
    tty: true
    networks:
      - demo
    ports:
      - 8000:8000

  "demo-postgres":
    image: postgres:latest
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - demo
    ports:
      - 5432:5432
    container_name: "demo-postgres"

networks:
  demo:
