version: '3'
services:

  "demo-nginx":
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./:/mnt
    depends_on:
      - demo-api
    networks:
      - demo

  "demo-api":
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
       - ./:/mnt
    # entrypoint: "/bin/bash -c './demo/start.bash'"
    entrypoint: "/bin/bash -c './start-v1.bash'"
    stdin_open: true
    tty: true
    networks:
      - demo

  "demo-api-v2":
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
       - ./:/mnt
    # entrypoint: "/bin/bash -c './demo/start.bash'"
    entrypoint: "/bin/bash -c './start-v2.bash'"
    stdin_open: true
    tty: true
    networks:
      - demo

  "demo-postgres":
    image: postgres:latest
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - demo
    ports:
      - 5432:5432
    container_name: "demo-postgres"

networks:
  demo:
